import Head from 'next/head'
import Header from "./Header";
const Layout = (props) => {
    return (
        <>
            <Head>
                <title>Knowledge Base</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="initial-scale=1, width=device-width" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous"></link>
                <link
                    rel="stylesheet"
                    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
                ></link>
                <link
                    rel="stylesheet"
                    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
                ></link>
                <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet"></link>
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css" integrity="sha512-NhSC1YmyruXifcj/KFRWoC561YpHpc5Jtzgvbuzx5VozKpWvQ+4nXhPdFgmx8xqexRcpAglTj9sIBWINXa8x5w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
            </Head>
            <Header />
            <main>
                {props.children}
            </main>
            <style jsx global>{`
            :root{
                --dark:#000;
                --light: #FFFF;
                --bg: #f7f9fc;
                --txt: #808080;
            }
            html {
                box-sizing: border-box;
                font-size: 62.56%;
              }
              *, *:before, *:after {
                box-sizing: inherit;
              }
              body{
                
                font-family: 'Source Sans Pro',Helvetica,Arial,Sans-Serif;
                color: #000;
                font-size: 1.8rem;
                background-color: var(--bg);
              }
            h1,h2,h3,h4{
                font-family: 'Fjalla One', 'Roboto';
            }
            ul,li {
                padding: 0;
                margin: 0;
                list-style: none;
            }
            p{
                font-size: 1.6rem;
            }
            a{
                text-decoration: none;
            }
            ul{
                list-decoration: none;
            }
            .box{
                background-color: #FFF;
                border-radius: 4px;
                border: thin solid #e6e6e6;
            }
            
        `}
            </style>
        </>
    )

}

export default Layout;